// ============================================================================
// SPARE PARTS CATEGORIES AND ITEM TYPES
// ============================================================================

/**
 * Valid item types in the stock ledger system
 */
export const ITEM_TYPES = ['RM', 'PM', 'SFG', 'FG', 'SPARE'] as const;
export type ItemType = typeof ITEM_TYPES[number];

/**
 * Spare parts categories with their subcategories
 */
export const SPARE_CATEGORIES = {
  BEARING: {
    label: 'Bearing',
    subcategories: ['BALL_BEARING', 'ROLLER_BEARING', 'THRUST_BEARING', 'BUSH']
  },
  SEAL: {
    label: 'Seal',
    subcategories: ['O_RING', 'OIL_SEAL', 'GASKET', 'PACKING']
  },
  ELECTRICAL: {
    label: 'Electrical',
    subcategories: ['MOTOR', 'RELAY', 'SENSOR', 'SWITCH', 'CONTACTOR', 'FUSE']
  },
  HYDRAULIC: {
    label: 'Hydraulic',
    subcategories: ['PUMP', 'VALVE', 'CYLINDER', 'HOSE', 'FITTING']
  },
  PNEUMATIC: {
    label: 'Pneumatic',
    subcategories: ['CYLINDER', 'VALVE', 'FRL', 'FITTING', 'TUBE']
  },
  HEATING: {
    label: 'Heating',
    subcategories: ['HEATER_BAND', 'THERMOCOUPLE', 'CARTRIDGE_HEATER', 'NOZZLE_HEATER']
  },
  MECHANICAL: {
    label: 'Mechanical',
    subcategories: ['GEAR', 'SHAFT', 'COUPLING', 'BELT', 'CHAIN', 'SPROCKET']
  },
  MOLD_PARTS: {
    label: 'Mold Parts',
    subcategories: ['EJECTOR_PIN', 'GUIDE_PIN', 'GUIDE_BUSH', 'SPRING', 'COOLING_FITTING']
  },
  CONSUMABLE: {
    label: 'Consumable',
    subcategories: ['LUBRICANT', 'COOLANT', 'FILTER', 'GREASE']
  },
  FASTENER: {
    label: 'Fastener',
    subcategories: ['BOLT', 'NUT', 'SCREW', 'WASHER', 'ALLEN_KEY']
  },
  OTHER: {
    label: 'Other',
    subcategories: ['GENERAL']
  }
} as const;

export type SpareCategory = keyof typeof SPARE_CATEGORIES;
export type SpareSubCategory<T extends SpareCategory> = typeof SPARE_CATEGORIES[T]['subcategories'][number];

/**
 * Get all spare category keys
 */
export const getSpareCategoryKeys = (): SpareCategory[] => {
  return Object.keys(SPARE_CATEGORIES) as SpareCategory[];
};

/**
 * Get category label
 */
export const getSpareCategoryLabel = (category: SpareCategory): string => {
  return SPARE_CATEGORIES[category]?.label || category;
};

/**
 * Get subcategories for a category
 */
export const getSpareSubCategories = (category: SpareCategory): readonly string[] => {
  return SPARE_CATEGORIES[category]?.subcategories || [];
};

/**
 * Format subcategory for display (replace underscores with spaces)
 */
export const formatSubCategory = (subCategory: string): string => {
  return subCategory.replace(/_/g, ' ');
};

/**
 * Valid units of measure for spare parts
 */
export const SPARE_UNITS = ['PCS', 'NOS', 'KG', 'LTR', 'MTR', 'SET'] as const;
export type SpareUnit = typeof SPARE_UNITS[number];

/**
 * Get category short code (first 3 characters)
 */
export const getCategoryShortCode = (category: string): string => {
  return category.slice(0, 3).toUpperCase();
};

/**
 * Generate item code for spare part
 * Format: SPARE-{CATEGORY_3_CHARS}-{SEQUENCE}
 * This is a helper for frontend preview - actual code is generated by DB function
 */
export const generateSpareCodePreview = (category: string, existingCount: number = 0): string => {
  const shortCode = getCategoryShortCode(category);
  const sequence = String(existingCount + 1).padStart(3, '0');
  return `SPARE-${shortCode}-${sequence}`;
};

/**
 * All flat subcategories list (for search/filter)
 */
export const getAllSubCategories = (): string[] => {
  const allSubCategories: string[] = [];
  for (const category of Object.values(SPARE_CATEGORIES)) {
    allSubCategories.push(...category.subcategories);
  }
  return allSubCategories;
};

/**
 * Find category by subcategory
 */
export const findCategoryBySubCategory = (subCategory: string): SpareCategory | null => {
  for (const [category, data] of Object.entries(SPARE_CATEGORIES)) {
    if ((data.subcategories as readonly string[]).includes(subCategory)) {
      return category as SpareCategory;
    }
  }
  return null;
};

export default {
  ITEM_TYPES,
  SPARE_CATEGORIES,
  SPARE_UNITS,
  getSpareCategoryKeys,
  getSpareCategoryLabel,
  getSpareSubCategories,
  formatSubCategory,
  getCategoryShortCode,
  generateSpareCodePreview,
  getAllSubCategories,
  findCategoryBySubCategory,
};


